### ISSUE TITLE
文本相似度系统-java版本

### ISSUE THREAD

**Issue by hyj1321676632** [Emmitte/DocDistance#1]

**Comment by Emmitte** [comment]
你好，该文件为word2vec训练中文后生成的.bin模型，由于生成的模型文件较大(单个文件已超过100M)，我无权限上传，你可以找一个中文语料通过word2vec训练出一个.bin模型文件，若文章只有英文可使用model/vectors.bin文件。






在 2018-03-31 16:32:58，"hyj1321676632" <notifications@github.com> 写道：


Word2VEC vec = new Word2VEC();
vec.loadJavaModel("library/javaSkip1");

您好。请问"library/javaSkip1"这条路径下存放的是什么文件呢？
